version: '3.4'

services:
  node_1:
    image: solanalabs/solana:v1.6.10
    environment:
      - MONIKER=node_1
      - METADATA_URL=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
      # - SNAPSHOT_BASE_URL=http://135.181.60.250/akash
      # - SNAPSHOT_FORMAT=tar
    ports:
      - "8899:8899"
    env_file:
      - .env
    volumes:
      - ./node-data:/root/.akash
  node_2:
    image: solanalabs/solana:v1.6.10
    environment:
      - MONIKER=node_1
      - METADATA_URL=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
    ports:
      - "8898:8899"
    env_file:
      - .env
    volumes:
      - ./node-data:/root/.akash
  node_3:
    image: solanalabs/solana:v1.6.10
    environment:
      - MONIKER=node_1
      - METADATA_URL=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
    ports:
      - "8897:8899"
    env_file:
      - .env
    volumes:
      - ./node-data:/root/.akash
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node_1
      - node_2
      - node_3
