---
version: "2.0"

services:
  node_1:
    image: solanalabs/solana:v1.6.10
    expose:
      - port: 8899
        as: 8899
        proto: tcp
        to:
          - global: true
  node_2:
    image: solanalabs/solana:v1.6.10
    expose:
      - port: 8899
        as: 8898
        proto: tcp
        to:
          - global: true
  node_3:
    image: solanalabs/solana:v1.6.10
    expose:
      - port: 8899
        as: 8897
        proto: tcp
        to:
          - global: true
  nginx:
    image: ghcr.io/tombeynon/nginx-dynamic-lb:v0.0.2
    # build: ./nginx
    env: 
      - HOST=mylbdomain.com
      - HOSTS=node_1:8899, node_2:8898, node_3:8897
    expose:
      - port: 80
        as: 8080
        proto: tcp
        to:
          - global: true

profiles:
  compute:
    solana:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    nginx:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        solana: 
          denom: uakt
          amount: 10
        nginx: 
          denom: uakt
          amount: 10

deployment:
  node_1:
    akash:
      profile: solana
      count: 1
  node_2:
    akash:
      profile: solana
      count: 1
  node_3:
    akash:
      profile: solana
      count: 1
  nginx:
    akash:
      profile: nginx
      count: 1
