---
version: "2.0"

services:
  node:
    image: ghcr.io/tombeynon/nginx-dynamic-lb:v0.0.2 # our image, first need to push image to docker hub
    env:
      - HOST=mylbdomain.com # HOST-DOMAIN
      - HOSTS=<node_deploy_1:port,node_deploy_2:port...> # NODE_1:PORT_1,NODE_2:PORT_2...
    expose:
      - port: 80
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 0.5Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 2 #COUNT_OF_NODES
